# Generated by Django 4.1.13 on 2024-06-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
